//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISApteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public int StockID { get; set; }
        public int CountBill { get; set; }
        public int DoctorID { get; set; }
        public string ClientName { get; set; }
        public string ShortClientName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
