//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISApteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Bill = new HashSet<Bill>();
        }
    
        public int StockID { get; set; }
        public int SupplierID { get; set; }
        public int CountInStock { get; set; }
        public string DrugName { get; set; }
        public int DrugTypeID { get; set; }
        public string Description { get; set; }
        public int StockShelf { get; set; }
        public string DrugImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual DrugType DrugType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
